os: osx
language: rust
rust:
- stable
script:
- cargo build --release
deploy:
  provider: releases
  api_key:
    secure: Jpi9yYojjO92zFU6ZO1rgbYqrYaZ098aWvtRVeJFFKIwe0p9dfHZ1X6BK6vp7pBub1PKdQuglTp9uvjvkwBFO/Q2OYWxPnRXSZ9YBLE6nkT0YoSHktrePAiFXr+b6JNGv/06gCnfiBzwIHobO0vMl0W9cv5kl7+dai42PrFWPdbJ3voUc3mrMovOXmfAfEBVV2eYE7Lp2G4A0iSUw/x1MTu5uLqsVUSJAv8lgKlo1jHi1TxWE9c9Ipk8Rrc6HstMHcNpYv5kWuYiYpFZh3RpLkZW/V5RM86VnWX8hM2IdkdUavYpMKopSeETHHRnegrLBAaSBHYb04FIqFioGozSuEJiR/vsuxQsA7HUMlHJv5bLyXqsajfgnNjcpbirVQpnq8WfvQtp4HqevOgEk+q0kKuzE+rTOUurK0RB6J2OF05CUEg7d6CCjCR47IcOnCnU8EqHsDCRmfoIYhiwcwy4E3t7CxTALRGnLTwbjkHEU3wMV5VWaGrNE7RlNawrtigkhDD4B5GIpj9Fe10uj/kGWshL5/wNWkzFSxRLKujEvNa5RSfst/vg8eTd/qKMebndIHaJxuji24oJwTt+ercebj+475ef6ENIv57wiMAguOy9SemRDH9qDK7+7fEIn/QXPjeDpekjY+aMK9wmEsRzeYVylXGvaxIO36lW024xyfU=
  file: "./target/release/trash"
  on:
    repo: ameistad/trash
    tags: true
